spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/business_db
    username: app_user
    password: app_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none        # flyway manages schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    create-schemas: true
    clean-disabled: false
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: myGroup
