openapi: 3.0.3
info:
  title: Example Echo API
  version: 1.0.0
servers:
  - url: /
paths:
  /echo:
    post:
      summary: Echo a string
      operationId: sendString
      tags:
        - echo
      requestBody:
        description: A plain string to echo
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EchoRequest'
      responses:
        '200':
          description: OK - echoed string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EchoResponse'
    get:
      summary: Get all messages from the table
      operationId: getMessages
      tags:
        - echo
      responses:
        '200':
          description: OK - list of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EchoResponse'


components:
  schemas:
    EchoRequest:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the request.
        message:
          type: string
          description: The string content to be echoed.
      required:
        - id
        - message

    EchoResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          description: Unique identifier from the request.
        message:
          type: string
          description: The echoed string content.
        topic:
          type: string
          description: The echoed string content.

